### PR TITLE
Description of coordinate system

### LINKED ISSUE #24: Should have a page explaining the coordinate system
It's a little unusual, and a point of confusion for folks.

### PR DESCRIPTION
**Pull request by iangilman**
We won't land this until after https://github.com/openseadragon/openseadragon/pull/446 lands. 

Fixes #24.

### CODE REVIEW

**Comment by iangilman** [comment]
@avandecreme I've added a live demo now. Just one image for the time being, but it shows the three coordinate systems.

**Comment by avandecreme** [comment]
Ok, I just tested it. It looks good except that the viewport coordinates should be decimals. Maybe add 2 digits?
That might require some modifications of the Point class.

**Comment by iangilman** [comment]
@avandecreme Thanks! And yes, exactly that modification already exists in the "collections" branch, so once it's released and we publish this page, we'll get the extra two digits.

**Comment by iangilman** [comment]
@avandecreme okay, I've added the two zoom systems to the example. I've also added a mention of @msalsbery's imaging helper plugin.

**Comment by iangilman** [comment]
Added additional multi-image information.

**Comment by avandecreme** [comment]
What about transforming ImageSequence, ImageReferenceStrip and TileSourceCollections to plugins?

**Comment by iangilman** [comment]
Indeed, seems like a good idea.

**Comment by iangilman** [comment]
Filed https://github.com/openseadragon/openseadragon/issues/649 for the plugin suggestion.

**Comment by iangilman** [comment]
Added in2white and the SVG overlay plugin.

**Pull request merged**
