### PR TITLE
In-the-wild entry: Urbano Monte 1587 World Map

### PR DESCRIPTION
**Pull request by tommypreger**

### CODE REVIEW

**Comment by tommypreger** [comment]
Pull request after suggestion by @iangilman 
https://github.com/openseadragon/openseadragon/issues/381

Maybe I did this a bit prematurely... I haven't tested my site extensively. You guys be the judge if it is good enough to showcase. The URL might change later on, but I don't mind just updating this link when/if that happens.

**Review by iangilman — CHANGES_REQUESTED** [review]
It certainly seems ready to share as far as I'm concerned! I would appreciate it if you update it in the future if the URL changes. 

One thing: we're keeping the lists alphabetized. Can you move the listing so it's in the right alphabetical order? 

Thank you for adding this!

**Review by iangilman — APPROVED** [review]
I'll take care of the alphabetization myself after merging.

**Comment by iangilman** [comment]
Deployed: http://openseadragon.github.io/examples/in-the-wild/#mapping

**Pull request merged**
