### PR TITLE
Add link to Lunch

### PR DESCRIPTION
**Pull request by tokee**
The [Lunch](http://labs.statsbiblioteket.dk/juxta/lunch/) installation superimposes one OpenSeadragon on another, creating a loupe/x-ray/spyglass effect of lunch trays before & after lunch

### CODE REVIEW

**Comment by iangilman** [comment]
Very cool project! How did you make the circular clipping region? That would be a cool plugin if you can generalize it. :)

**Comment by iangilman** [comment]
Deployed: http://openseadragon.github.io/examples/in-the-wild/#storytelling

**Comment by tokee** [comment]
Thank you, @iangilman.

It took me far too long to figure out the circular clipping, but as so many of these things the resulting solution turned out to be very simple:

The visual in itself is simple CSS: Setting `border-radius: 50%;` on a `div` makes it circular and setting `box-shadow: 0 0 5px #ddd;` makes a border that does not affect the coordinates or size for the `div`, as opposed to the `border`-property that does affect it.

Using `shadow` instead of `border` made coordinate translation clean, with no need for offset-fiddling:
```
    var loupeRect_VE = new OpenSeadragon.Rect(loupeDiv.offsetLeft-baseDiv.offsetLeft, loupeDiv.offsetTop-baseDiv.offsetTop, loupeDiv.offsetWidth, loupeDiv.offsetHeight);
    var baseRect_V = baseView.viewerElementToViewportRectangle(loupeRect_VE);
    var baseRect_I = baseView.viewportToImageRectangle(baseRect_V);
    var loupeRect_V = loupeView.imageToViewportRectangle(baseRect_I)
    loupeView.fitBounds(loupeRect_V, true);
```
That's about it. The rest is setting up event handlers for mouse move, zoom & pan to keep updating the loupe-content.
As for writing a plugin... Maybe? The two collages must be the exact same size and I haven't really had any luck locating a similar pair-oriented dataset for another demo. I am afraid it is too specialized for general use?

**Comment by iangilman** [comment]
I see, clever! Yes, I suppose that is fairly specialized. For some reason I hadn't thought of using two synchronized viewers... I was imagining somehow doing it all in a single viewer, which would be neat, but no doubt more work.

At any rate, it's a delightful example of a clever use of OpenSeadragon :)

**Pull request merged**
