### PR TITLE
Added the Art Institute of Chicago to "in the wild"

### PR DESCRIPTION
**Pull request by MaxwellTG**
Click image to inspect artwork in an OSD viewer.

### CODE REVIEW

**Comment by iangilman** [comment]
Lovely! Please alphabetize it though :)

**Comment by MaxwellTG** [comment]
Now alphabetized!

**Comment by iangilman** [comment]
Beautiful!

**Comment by iangilman** [comment]
Deployed: http://openseadragon.github.io/examples/in-the-wild/

**Pull request merged**
