### PR TITLE
included new options (tileSize, fileFormat) on zoomify tilesource page

### PR DESCRIPTION
**Pull request by abrlam**

### CODE REVIEW

**Review by iangilman — CHANGES_REQUESTED** [review]
@Abrlam Awesome, thank you for doing this!

I think, rather than deploying this with the "coming soon" language, we should hold off on deploying it until the new OSD version is released. Can you update the PR so it's worded as if the new features are already released? One possibility would be to just have one code sample, but use comments to break it into required and optional parameters.

**Comment by abrlam** [comment]
@iangilman  Not a problem. I updated the page again based on your feedback. Let me know if further changes are needed.

**Review by iangilman — APPROVED** [review]
Perfect, thank you! We'll merge this when we release the next version :-)

**Comment by iangilman** [comment]
Merging for the 3.0 release!

**Pull request merged**
