### PR TITLE
Update in-the-wild.html

### PR DESCRIPTION
**Pull request by LarsLarson**
Added Great Basin Forensics to Science

### CODE REVIEW

**Comment by LarsLarson** [comment]
Sure, no worries.  Didn't know what the protocol is.

Chris

**Comment by LarsLarson** [comment]
With a little luck I changed the pull request.  Not very literate in GitHub!

**Comment by iangilman** [comment]
Perfect! Thank you :)

**Comment by iangilman** [comment]
Perfect! Thank you :)

Deployed: http://openseadragon.github.io/examples/in-the-wild/#science

**Pull request merged**
