### PR TITLE
Removed minZoomLevel, fixes #105

### LINKED ISSUE #105: Complex HTML overlay demo zooming issue
Once you zoom in, you can't zoom out anymore. 

http://openseadragon.github.io/examples/ui-overlays/

### PR DESCRIPTION
**Pull request by TMUND**
Removed minZoomLevel. Now you can zoom out all the way.

### CODE REVIEW

**Comment by iangilman** [comment]
Thank you! And published: 

http://openseadragon.github.io/examples/ui-overlays/

**Comment by iangilman** [comment]
@avandecreme And thanks for spotting the issue!

**Comment by avandecreme** [comment]
Ha, was easier to fix than I thought :)
There is still an issue: if you go to the next page and then back, the overlay is not coming back. (Actually, shouldn't it be present on all pages?)
It looks like an OSD bug though.

**Comment by avandecreme** [comment]
Thanks for filling the issue :)

**Pull request merged**
