### PR TITLE
add wellcomecollection to the "in the wild page"

### PR DESCRIPTION
**Pull request by jamesgorrie**
Adds the Wellcome Collection DZI to the list of wildness 🐗

### CODE REVIEW

**Comment by iangilman** [comment]
Looks great! One small thing: We're trying to keep it alphabetical, and it seems the St. Chad item (which should be alphabetized as 'Saint' I suppose) is out of place, which is probably what led you to add the Wellcome Collection below it. Would you mind moving yours up above World Digital Library? While you're at it, if you could move St. Chad as well we can avoid this confusion in the future :)

**Comment by jamesgorrie** [comment]
@iangilman sure thing - just did it.

Yea, I got a little confused as it seemed alphabetical until the last entry, so thought it was just a very nice coincidence of the order that people put them in.

**Comment by iangilman** [comment]
Yeah, that's how confusion creeps in! 

Thank you for sorting it out :)

**Comment by iangilman** [comment]
And deployed: 

http://openseadragon.github.io/examples/in-the-wild/

**Pull request merged**
