### PR TITLE
Update JSDoc conf and templates

### PR DESCRIPTION
**Pull request by avandecreme**
I updated the templates to the latest version from JSDoc and reintroduced our tweaks (CSS and precomputed syntax highlighting).
It goes with https://github.com/openseadragon/openseadragon/pull/905

### CODE REVIEW

**Comment by iangilman** [comment]
Thank you for doing this! Does it require any of the changes over in openseadragon/openseadragon? If so, we should land it when we next publish a new version.

**Comment by avandecreme** [comment]
Yes it should be merged for the next release.

**Comment by avandecreme** [comment]
I noticed #16 so I added the favicon from the browser plugin :)

**Comment by iangilman** [comment]
Sweet!

**Comment by iangilman** [comment]
OSD 2.2.0 is released and this is published: http://openseadragon.github.io/docs/

The new JSDoc is a lot faster!

**Pull request merged**
