### PR TITLE
Added the Smapshot project under in-the-wild.html#mapping

### PR DESCRIPTION
**Pull request by nicolas-heigvd**
Added the Smapshot project to the mapping section of the webpage in-the-wild.html

### CODE REVIEW

**Review by iangilman — CHANGES_REQUESTED** [review]
Wow, this is a really cool project! I've gone ahead and tweeted about it: 

https://twitter.com/openseadragon/status/1558201459501477888

Thank you for this PR! Can I ask one thing? Please move this new link up so it's alphabetized within this section.

**Comment by nicolas-heigvd** [comment]
@iangilman I fixed the order. Thanks for the hint.
And btw, thank you very much for the tweet!

**Review by iangilman — APPROVED** [review]
Awesome, thank you!

**Comment by iangilman** [comment]
And deployed! 

https://openseadragon.github.io/examples/in-the-wild/#mapping

**Pull request merged**
