### PR TITLE
add opacity-slider plugin

### PR DESCRIPTION
**Pull request by WasMachenSachen**
This adds the opacity slider plugin to the list.

additional information about the plugin can be found here: https://github.com/WasMachenSachen/openseadragon-opacity-slider

### CODE REVIEW

**Review by iangilman — CHANGES_REQUESTED** [review]
Fantastic! This is a great plugin. Thank you for adding it :) 

One small thing: We're trying to keep this list alphabetized. Can you please move it up under OpenSeadragonMultiRow?

**Comment by WasMachenSachen** [comment]
Yes that makes sense. Moved it!

**Review by iangilman — APPROVED** [review]
Lovely, thank you!

**Comment by iangilman** [comment]
Deployed: http://openseadragon.github.io/#plugins

**Pull request merged**
