### PR TITLE
Update in-the-wild.html

### PR DESCRIPTION
**Pull request by regisrob**
Added an example from the Biblissima portal: using Openseadragon to display static images and IIIF images from Gallica and Mandragore, Bibliothèque nationale de France)

### CODE REVIEW

**Comment by regisrob** [comment]
Oups! Sure, I should review my alphabet :)

**Comment by iangilman** [comment]
Beautiful. Thank you for adding this!

**Comment by iangilman** [comment]
Deployed! http://openseadragon.github.io/examples/in-the-wild/#history

**Comment by regisrob** [comment]
thanks!

**Pull request merged**
