### PR TITLE
Fix overlays demos.

### PR DESCRIPTION
**Pull request by avandecreme**

### CODE REVIEW

**Comment by avandecreme** [comment]
The complex HTML demo is still not working very well but I don't have time to dig into it for now.

**Comment by iangilman** [comment]
Awesome; thank you for spotting and fixing this. We'll land this when OSD 2.1.0 releases. 

What is the issue you're seeing with the complex HTML demo?

**Comment by avandecreme** [comment]
Once you zoom in, you can't zoom out anymore.
This is reproducible on the published version as well: http://openseadragon.github.io/examples/ui-overlays/

**Comment by iangilman** [comment]
Gotcha; thanks for pointing it out!

**Pull request merged**
