### PR TITLE
Update existing overlay doc.

### PR DESCRIPTION
**Pull request by avandecreme**
The next step is to document overlays with rotation.

### CODE REVIEW

**Comment by iangilman** [comment]
Cool. Besides rotation are there additional features we want to highlight here now?

So far looks good. We'll land with the next release.

**Comment by avandecreme** [comment]
> Cool. Besides rotation are there additional features we want to highlight here now?

Not that I can think of. Looks ready to me.

**Comment by iangilman** [comment]
Cool, looks good!

**Comment by iangilman** [comment]
OSD 2.2.0 is released and this is published: http://openseadragon.github.io/examples/ui-overlays/

**Pull request merged**
