### PR TITLE
added OSDMeasure to plugins

### PR DESCRIPTION
**Pull request by verrochi92**

### CODE REVIEW

**Review by iangilman — CHANGES_REQUESTED** [review]
Fantastic! One small thing: While we are trying to keep it alphabetized, we are ignoring the `OpenSeadragon` for alphabetization purposes, since so many (but not all) of the plugins include it. I figure we should do the same for the `OSD` in your plugin. Can you please move it up under OpenSeadragonMagnifier?

**Comment by verrochi92** [comment]
All set!

**Review by iangilman — APPROVED** [review]
Lovely, thank you!

**Comment by iangilman** [comment]
Deployed: https://openseadragon.github.io/#plugins

**Pull request merged**
