### PR TITLE
Update in-the-wild.html

### PR DESCRIPTION
**Pull request by jmlatgpixel**
This time it should be OK.
J Escravana

### CODE REVIEW

**Comment by jmlatgpixel** [comment]
Done.
J Escravana

**Review by iangilman — CHANGES_REQUESTED** [review]
Great! A couple comments: 

* What's the name of your site? It seems like that should be part of the title.
* You have every word but "resolution" capitalized... I figure you should capitalize that one as well.
* We're trying to keep these lists alphabetized; can you put your new item in the right location alphabetically? 
* A lot of our items have just one example, though I see we have some that have more. That said, five might be a bit much. Maybe pick your top 3? 

Thank you for putting this together!

**Comment by jmlatgpixel** [comment]
Hello @iangilman 

I have to confess that the edition of my pull request not because of the code, just because it's a complex process (I'm new to Github). Anyway it's done according to your suggestions.

 * What's the name of your site? It seems like that should be part of the title.
 - Gpixel.orG (the domain name)
 * You have every word but "resolution" capitalized... I figure you should capitalize that one as well.
 - Removed from title
 * We're trying to keep these lists alphabetized; can you put your new item in the right location alphabetically?
- Done
 * A lot of our items have just one example, though I see we have some that have more. That said, five might be a bit much. Maybe pick your top 3?
 - Narrowed to 3

Thanks,
J Escravana

**Review by iangilman — APPROVED** [review]
Perfect! I appreciate your taking the time to learn how to make a pull request; you did a great job, and hopefully it will be a useful skill for you. 

These examples are a great addition to our collection... Thank you!

**Comment by iangilman** [comment]
Merged and deployed: https://openseadragon.github.io/examples/in-the-wild/#mapping

**Pull request merged**
