### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by KTGLeiden**
Added Screenshot plugin link. Demo is included in the readme.md of the repo.

~koen

### CODE REVIEW

**Comment by avandecreme** [comment]
Good work! I will let @iangilman merge it when he is back.

A comment regarding the troubleshooting part: this will only work if the server providing the tiles as the CORS headers enabled.
You can read more about it here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by KTGLeiden** [comment]
Thx :)
Yes, of course.. I will add that information as well ;)

~Koen

**Comment by iangilman** [comment]
Thank you! Deployed :)

**Comment by KTGLeiden** [comment]
Cool! :)

**Pull request merged**
