### PR TITLE
Adding Zoomable and PHP Deep Zoom Tools

### PR DESCRIPTION
**Pull request by iangilman**

### CODE REVIEW

**Comment by iangilman** [comment]
@nfabre, FYI; linking to your tool. 

@abrlam What would you think about providing an API to your tool? Or at least providing instructions for how to access the DZI directly for people who don't want to use the embed?

**Comment by abrlam** [comment]
Hi Ian,

Thank you for adding my site to your repository!

I think I could do the latter in the short run, sometime after fixing the uploading issues mentioned in issue #89.

How's it going on your end?  Are you guys launching the site soon? 


     On Monday, March 30, 2015 6:23 PM, Ian Gilman <notifications@github.com> wrote:
   

 @nfabre, FYI; linking to your tool. @abrlam What would you think about providing an API to your tool? Or at least providing instructions for how to access the DZI directly for people who don't want to use the embed? —

**Comment by iangilman** [comment]
@abrlam Awesome. Let me know when you have the instructions together, so I can link to them. 

How's it going with ZoomHub? Slow, unfortunately...the people who know what they are doing are busy with their day jobs. I remain hopeful though. 

Meanwhile, things are going well over here in OpenSeadragon land...getting ready to release version 2.0.0 with multi-image support!

**Comment by iangilman** [comment]
Published: http://openseadragon.github.io/examples/creating-zooming-images/

**Pull request merged**
