### PR TITLE
Update in-the-wild.html

### PR DESCRIPTION
**Pull request by sbalci**
Patoloji Atlası is a bilingual histopathology atlas contains whole slide images. Here I convert svs images with vips. And use them in openseadragon websites.
https://github.com/openseadragon/openseadragon/issues/34#issuecomment-1593719053

### CODE REVIEW

**Review by iangilman — APPROVED** [review]
Lovely, thank you!

**Comment by iangilman** [comment]
@sbalci I hope you don't mind, I made a few small changes to the wording and formatting: https://github.com/openseadragon/site-build/commit/51a5613ed57514a52093ae1be5f12d013fef3b1d

**Comment by iangilman** [comment]
Deployed: https://openseadragon.github.io/examples/in-the-wild/#science

**Comment by sbalci** [comment]
Thank you 🎉

**Pull request merged**
