### PR TITLE
IIIF Example to HTTPS

### PR DESCRIPTION
**Pull request by jpstroop**
I hope this wasn't broken long!

### CODE REVIEW

**Comment by iangilman** [comment]
It seems to be working with the old data, so I guess that means it wasn't broken long.

At any rate, thank you for updating! I appreciate it. :)

**Comment by iangilman** [comment]
Deployed: 

http://openseadragon.github.io/examples/tilesource-iiif/

**Comment by jpstroop** [comment]
Thanks @iangilman! Maybe you had something cached or we had have different browsers? It was broken for me.

**Comment by iangilman** [comment]
Cool... well, good to have it updated. :)

**Pull request merged**
