### PR TITLE
Added a page for Zoomify.

### LINKED ISSUE #148: Create example page for Zoomify tile source
...and link it from the front page of course.

I suppose to do this we'll need a nice image in Zoomify format. @foobarable any thoughts on where to get such a thing?

### PR DESCRIPTION
**Pull request by Daniel-KM**
Hi,

This fix fixes #148 and #149, so [v2.2.2](https://github.com/openseadragon/site-build/milestone/3) is ready?

Daniel Berthereau
Infodoc & Knowledge management

### CODE REVIEW

**Comment by iangilman** [comment]
Wow, this is beautiful! Thank you for doing it, and for doing such a fine job of it :)

I'd say this milestone is ready on this end, but we're still waiting on https://github.com/openseadragon/openseadragon/issues/1094 over on the main repo. I'll merge this once that's done. 

Thanks again!

**Comment by iangilman** [comment]
👍 for the updated package URL.

**Comment by iangilman** [comment]
Looks like there's another Zoomify conversion option here: 

http://www.zoomify.com/free.htm

...and I understand Photoshop now has a Zoomify export built in. 

Those are probably both worth mentioning on the "Creating" page. 

...and no, we haven't forgotten about this patch! It's just taking a while to get the next OSD release finished up.

**Comment by Daniel-KM** [comment]
I added these links, even if I prefer not to make free advert for proprietary software.

**Comment by iangilman** [comment]
@Daniel-KM Thank you. I think it's important to share the tools available, and these provide some user friendly alternatives. Of course I look forward to there being more open source options as well! Speaking of which, it sounds like @michaelw3 may be working on a user friendly tiler (see this comment: https://github.com/openseadragon/openseadragon/issues/1207#issuecomment-309231063). 

Btw, sorry this release is taking so long... been slammed with other work, and I've got a little more debugging to do (unrelated to Zoomify), but hopefully soon!

**Comment by iangilman** [comment]
We're releasing 2.3.0, so merging now... thanks again for this patch!

**Pull request merged**
