### PR TITLE
removed zoomo, added tools/plugins in zoomable

### PR DESCRIPTION
**Pull request by abrlam**
PR to update the entry in zoomable and zoomo.

### CODE REVIEW

**Comment by iangilman** [comment]
There's an odd merge conflict here... I'm not sure why it thinks this is a conflict at all. Anyway, can you take a look?

**Comment by abrlam** [comment]
Same here, that was an odd conflict.  Anyway, I resolved it.  Thank you again.

**Comment by iangilman** [comment]
Great, thank you!

**Comment by iangilman** [comment]
Deployed: http://openseadragon.github.io/examples/creating-zooming-images/

**Pull request merged**
